name: Bug Report
description: Create a bug report to help us find and fix bugs!
title: "[Bug] "
labels: [bug]
body:
- type: checkboxes
  attributes:
    label: Before Reporting
    options:
    - label: I found no existing issues matching my bug
      required: true
    - label: I completely restarted Steam and checked if the bug is still there
      required: true
    - label: I have checked if I use the latest version
      required: true
- type: textarea
  attributes:
    label: Describe the Bug!
    description: |
      A clear and concise description of the bug.

      Tip: You can attach images by clicking this area to highlight it and then dragging files in.
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected Behavior
    description: A clear and concise description of what you expected to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. Open modal
      2. Click on dropdown
      3. Scroll down
      4. See bug...
  validations:
    required: true
- type: dropdown
  attributes:
    label: Operating System
    options:
      - Windows
      - Linux
  validations:
    required: true