name: Bug Report
description: Create a bug report to help us find and fix bugs!
title: "[Bug] "
type: "Bug"
labels: [bug]
projects: "SpaceTheme/3"
assignees: SpaceEnergy
body:
- type: checkboxes
  attributes:
    label: I checked the following before reporting a bug
    description: Please check the following before reporting a bug. This helps us to quickly identify and resolve issues.
    options:
    - label: I found no existing issues matching my bug
      required: true
    - label: I found no existing issues matching my bug on the [Millennium Repo](https://github.com/shdwmtr/millennium/issues)
      required: true
    - label: I restarted Steam completely and checked if the bug is still there
      required: true
    - label: I use the Steam Beta
      required: true
    - label: I use the latest theme version
      required: true
    - label: I've ticked the checkboxes without reading their contents
- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing.
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1. Open modal
      2. Click on dropdown
      3. Scroll down
      4. See bug...
  validations:
    required: true
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.