name: Attach ZIP to Release

on:
  release:
    types: [published]

jobs:
  attach-zip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create ZIP file
        run: |
          zip -r SpaceTheme_for_Steam.zip . \
            -x "*.git*" "*.github*" "_assets/*" "README.md"

      - name: Upload ZIP to the current release
        uses: softprops/action-gh-release@v1
        with:
          files: SpaceTheme_for_Steam.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}